import '../../style/globals.css';

export const metadata = {
    title : "NextJs",
    description : "Generated By NextJs",
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }